fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      ref: '4.4.0'
    'concat':
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      ref: '1.1.2'
  symlinks:
    supervisord: "#{source_dir}"
