# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# Converts the array to a csv string
#
# $array = [ 'string1', 'string2', 'string3' ]
#
# becomes:
#
# $string = "string1,string2,string3"
#
# ---- original file header ----
#
# @summary
#       Returns a sorted csv formatted string from an array in the form
#    VALUE1,VALUE2,VALUE3
#
#
Puppet::Functions.create_function(:'supervisord::array2csv') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    raise(Puppet::ParseError, "array2csv(): Wrong number of arguments " +
      "given (#{args.size} of 1)") if args.size < 1

    array = args[0]

    unless array.is_a?(Array)
      raise(Puppet::ParseError, 'array2csv(): Requires an Array')
    end

    sorted_array = array.sort
    result = ''

    sorted_array.each {|value|
      result += "#{value},"
    }

    return result.chop!
    
  
  end
end
